version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
      - ./data/MSSQL:/mssqldata
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Pass@word}
      ACCEPT_EULA: "Y"
