version: "3.9"

services:
  postgres-plv8:
    image: clkao/postgres-plv8
    container_name: postgres-plv8_container
    volumes:
      - ./data/postgres-plv8:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password1}
    ports:
      - "5432:5432"
    restart: unless-stopped
  postgres:
    image: postgres
    container_name: postgres_container
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password1}
    ports:
      - "5432:5432"
    restart: unless-stopped
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql_container
    ports:
      - "1433:1433"
    volumes:
      - ./data/MSSQL:/mssqldata
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Pass@word}
      ACCEPT_EULA: "Y"
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: "sample"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Pass@word}
    ports:
      - '3306:3306'
  ravendb:
    image: ravendb/ravendb
    container_name: ravendb_container
    ports:
      - "8080:8080"
    environment:
      RAVEN_ARGS: --Setup.Mode=None --Security.UnsecuredAccessAllowed=PublicNetwork --License.Eula.Accepted=true
  redis:
    image: bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended for development.
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - REDIS_DISABLE_COMMANDS=${REDIS_DISABLE_COMMANDS:-FLUSHDB,FLUSHALL}
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/bitnami/redis/data"
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 8025:8025 # web ui
      - 465:1025 # smtp server
  mongodb:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_DATABASE: sample
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-Pass@word}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
