version: "3.9"

services:
  postgres-plv8:
    image: clkao/postgres-plv8
    container_name: postgres-plv8_container
    volumes:
      - ./data/postgres-plv8:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
  postgres:
    image: postgres
    container_name: postgres_container
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql_container
    ports:
      - "1433:1433"
    volumes:
      - ./data/MSSQL:/mssqldata
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Pass@word}
      ACCEPT_EULA: "Y"
  ravendb:
    image: ravendb/ravendb
    container_name: ravendb_container
    ports:
      - "8080:8080"
    environment:
      RAVEN_ARGS: --Setup.Mode=None --Security.UnsecuredAccessAllowed=PublicNetwork --License.Eula.Accepted=true
  redis:
    image: bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended for development.
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - REDIS_DISABLE_COMMANDS=${REDIS_DISABLE_COMMANDS:-FLUSHDB,FLUSHALL}
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/bitnami/redis/data"
